In [16]:
from mxnet import autograd, nd
import numpy as np

In [17]:
x = nd.arange(4).reshape((4, 1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [18]:
x.attach_grad()

In [19]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [20]:
y.backward()

In [27]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [23]:
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [33]:
x.grad



[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [28]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [34]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [35]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [47]:
a


[1.1630785]
<NDArray 1 @cpu(0)>

In [44]:
a.grad


[1024.]
<NDArray 1 @cpu(0)>